# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-AI-MegaHAL
version:      1.00
version_from: lib/POE/Component/AI/MegaHAL.pm
installdirs:  site
requires:
    AI::MegaHAL:                   0.04
    Carp:                          0
    POE:                           0.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
